server:
  port: 8008
spring:
  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      autoOffsetReset: earliest
    #properties:
    #  security:
    #    protocol: SASL_PLAINTEXT
    #  sasl:
    #    mechanism: PLAIN
    #    jaas:
    #      config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="kafka@123";'
