server:
  port: 8023
logging:
  config: classpath:logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-executor-sample
      port: 9999
      logpath: /logs/xxl-job/jobhandler
      logretentiondays: 30
