server:
  port: 8020
  servlet:
    context-path: /shiro
# mysql配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&&characterEncoding=UTF-8&connectTimeout=1000&autoReconnect=true
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
