server:
  port: 8004
spring:
  # 配置数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.newbeedaly.com:3306/elasticjob?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: MyHikariCP
elasticjob:
  regCenter:
    #zookeeper 的ip:port
    serverLists: 127.0.0.1:2181
    #名命空间，自己定义就好了
    namespace: elasticjob
  # 若elastic-job-lite-ui中没有com.mysql.cj.jdbc.Driver驱动，需手动导入到lib目录
  tracing:
    type: RDB
  jobs:
    # 简单定时任务名称，自定义名称
    simpleElasticJob:
      #定时任务的全路径名
      elasticJobClass: cn.newbeedaly.elasticjob.job.MySimpleJob
      #定时任务执行的cron表达式
      cron: 0/5 * * * * ?
      #分片数量
      shardingTotalCount: 10
      #更新配置
      overwrite: true
      #任务监听器
      jobListenerTypes:
        - simpleJobListener
      # 分片参数
      shardingItemParameters: 0=0,1=1,2=2,3=3,4=4,5=5,6=6,7=7,8=8,9=9
      # 参数
      jobParameter: 2023-05-27
    # 简单定时任务名称，自定义名称
    dataFlowElasticJob:
      #定时任务的全路径名
      elasticJobClass: cn.newbeedaly.elasticjob.job.MyDataFlowJob
      #定时任务执行的cron表达式
      cron: 0/10 * * * * ?
      #分片数量
      shardingTotalCount: 1
      #更新配置
      overwrite: true
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      insertStrategy: NOT_EMPTY
      updateStrategy: NOT_EMPTY
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
