server:
  port: 8016
spring:
  application:
    name: redis
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 3000ms
    # redis配置 Lettuce 是一个可伸缩线程安全的 Redis 客户端，多个线程可以共享同一个 RedisConnection，它利用优秀 netty NIO 框架来高效地管理多个连接
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
# Redis 哨兵模式，替代上面的database、host、password、port
#    database: 1
#    password:
#    sentinel:
#      master: mymaster
#      # 逗号分隔, 逗号前后不要有空格
#      nodes: 192.168.1.110:26379,192.168.1.111:26379,192.168.1.112:26379
# Redis 集群模式，替代上面的database、host、password、port
#    password:
#    cluster:
#      nodes: 192.168.1.201:6379,192.168.1.202:6379,192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379,192.168.1.206:6379
